jobs:
  deploy:
    name: Deploy to remote server
    needs:
    - test
    - push-image
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Deploy Docker Image
      uses: appleboy/ssh-action@master
      with:
        command_timeout: 10m
        host: ${{ secrets.HOST }}
        key: ${{ secrets.SSH_KEY }}
        script: 'docker pull cjbi/admin3:latest

          docker rm -f admin3 || true

          docker run -p 8082:8080 -e JAVA_OPTS="-Dserver.servlet.context-path=/ -Dfile.encoding=UTF-8
          -Duser.timezone=GMT+8 -Dspring.jpa.hibernate.ddl-auto=create -Dspring.datasource.url=${{
          secrets.DS_JDBC_URL }} -Dspring.datasource.username=${{ secrets.DS_USERNAME
          }} -Dspring.datasource.password=${{ secrets.DS_PASSWORD }}" -d --name admin3
          cjbi/admin3:latest

          '
        username: ${{ secrets.SSH_USER }}
  push-image:
    name: Push Docker image
    needs:
    - test
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        cache: maven
        distribution: temurin
        java-version: '21'
    - continue-on-error: true
      name: Build Image with Maven
      run: 'export VITE_BASE_URI=

        cd admin3-ui && mvn -B install

        cd ../admin3-server

        mvn -B -Dmaven.test.skip=true spring-boot:build-image -Ddocker.image-name=cjbi/admin3:latest
        -Ddocker.username=${{ secrets.DOCKER_USERNAME }} -Ddocker.password=${{ secrets.DOCKER_PASSWORD
        }}

        '
    - continue-on-error: true
      name: Caching Maven Dependencies
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
  push-native-image:
    name: Push Docker native image
    needs:
    - test
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        cache: maven
        distribution: temurin
        java-version: '21'
    - continue-on-error: true
      name: Build Image with Maven
      run: 'export VITE_BASE_URI=

        cd admin3-ui && mvn -B install

        cd ../admin3-server

        mvn -B -Dmaven.test.skip=true -Pnative spring-boot:build-image -Ddocker.image-name=cjbi/admin3-native:latest
        -Ddocker.username=${{ secrets.DOCKER_USERNAME }} -Ddocker.password=${{ secrets.DOCKER_PASSWORD
        }}

        '
  test:
    name: Run tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        cache: maven
        distribution: temurin
        java-version: '21'
    - continue-on-error: true
      name: Build Image with Maven
      run: 'mvn -B test

        '
    - continue-on-error: true
      name: Caching Maven Dependencies
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
name: CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
