jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        cache: maven
        distribution: temurin
        java-version: '21'
    - continue-on-error: true
      name: Build Image Test with Maven
      run: 'mvn -B test

        '
    - continue-on-error: true
      name: Caching Maven Dependencies
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
name: Maven Test
on:
  repository_dispatch:
    types: trigger-ga___maven-test.yml
