jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Deploy Docker Image
      uses: appleboy/ssh-action@master
      with:
        command_timeout: 10m
        host: ${{ secrets.HOST }}
        key: ${{ secrets.SSH_KEY }}
        script: 'docker pull cjbi/admin3:latest

          docker rm -f admin3 || true

          docker run -p 8082:8080 -e JAVA_OPTS="-Dserver.servlet.context-path=/ -Dfile.encoding=UTF-8
          -Duser.timezone=GMT+8 -Dspring.jpa.hibernate.ddl-auto=create -Dspring.datasource.url=${{
          secrets.DS_JDBC_URL }} -Dspring.datasource.username=${{ secrets.DS_USERNAME
          }} -Dspring.datasource.password=${{ secrets.DS_PASSWORD }}" -d --name admin3
          cjbi/admin3:latest

          '
        username: ${{ secrets.SSH_USER }}
name: Deploy to remote server
on:
  repository_dispatch:
    types: trigger-ga___schedule.yml
